# Generated by Django 3.0.3 on 2021-04-09 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
        migrations.DeleteModel(
            name='rating_review',
        ),
    ]
